In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support,classification_report

In [2]:
df = pd.read_csv("Datasets/iris.csv",names = ['sepal_length','sepal_width','petal_length','petal_width','class'])

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
6             4.6          3.4           1.4          0.3     Iris-setosa
7             5.0          3.4           1.5          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
9             4.9          3.1           1.5          0.1     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
11            4.8          3.4           1.6          0.2     Iris-setosa
12            4.8          3.0           1.4          0.1     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
15            5.7          4.4           1.5          0.4     Iris-setosa
16            5.4          3.9           1.3          0.4     Iris-setosa
17            5.1          3.5           1.4          0.3     Iris-setosa
18            5.7          3.8           1.7          0.3     Iris-setosa
19            5.1          3.8           1.5          0.3     Iris-setosa
20            5.4          3.4           1.7          0.2     Iris-setosa
21            5.1          3.7           1.5          0.4     Iris-setosa
22            4.6          3.6           1.0          0.2     Iris-setosa
23            5.1          3.3           1.7          0.5     Iris-setosa
24            4.8          3.4           1.9          0.2     Iris-setosa
25            5.0          3.0           1.6          0.2     Iris-setosa
26            5.0          3.4           1.6          0.4     Iris-setosa
27            5.2          3.5           1.5          0.2     Iris-setosa
28            5.2          3.4           1.4          0.2     Iris-setosa
29            4.7          3.2           1.6          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
120           6.9          3.2           5.7          2.3  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
123           6.3          2.7           4.9          1.8  Iris-virginica
124           6.7          3.3           5.7          2.1  Iris-virginica
125           7.2          3.2           6.0          1.8  Iris-virginica
126           6.2          2.8           4.8          1.8  Iris-virginica
127           6.1          3.0           4.9          1.8  Iris-virginica
128           6.4          2.8           5.6          2.1  Iris-virginica
129           7.2          3.0           5.8          1.6  Iris-virginica
130           7.4          2.8           6.1          1.9  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
132           6.4          2.8           5.6          2.2  Iris-virginica
133           6.3          2.8           5.1          1.5  Iris-virginica
134           6.1          2.6           5.6          1.4  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
136           6.3          3.4           5.6          2.4  Iris-virginica
137           6.4          3.1           5.5          1.8  Iris-virginica
138           6.0          3.0           4.8          1.8  Iris-virginica
139           6.9          3.1           5.4          2.1  Iris-virginica
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142      

In [4]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [5]:
X = df.drop('class',axis=1)
Y = df['class']


In [6]:
xtrain, xtest, ytrain, ytest = train_test_split(X,Y,test_size = 0.3, random_state=0)
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(105, 4)
(105,)
(45, 4)
(45,)


In [7]:
model = LogisticRegression()
model.fit(xtrain, ytrain)


/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [8]:
clf =  LogisticRegression().fit(xtrain,ytrain)
ypred=clf.predict(xtest)
print("Accuracy:",accuracy_score(ytest, ypred))
print("Error Rate:",1-accuracy_score(ytest, ypred))

Accuracy: 0.888888888889
Error Rate: 0.111111111111


/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [9]:
confusion_matrix(ytest,ypred)

array([[16,  0,  0],
       [ 0, 13,  5],
       [ 0,  0, 11]])

In [10]:
print(classification_report(ytest,ypred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.72      0.84        18
 Iris-virginica       0.69      1.00      0.81        11

      micro avg       0.89      0.89      0.89        45
      macro avg       0.90      0.91      0.88        45
   weighted avg       0.92      0.89      0.89        45



In [11]:
le = preprocessing.LabelEncoder()
df2 = df.apply(le.fit_transform)
df2

sepal_length  sepal_width  petal_length  petal_width  class
0               8           14             4            1      0
1               6            9             4            1      0
2               4           11             3            1      0
3               3           10             5            1      0
4               7           15             4            1      0
5              11           18             7            3      0
6               3           13             4            2      0
7               7           13             5            1      0
8               1            8             4            1      0
9               6           10             5            0      0
10             11           16             5            1      0
11              5           13             6            1      0
12              5            9             4            0      0
13              0            9             1            0      0
14             15           19             2            1      0
15             14           22             5            3      0
16             11           18             3            3      0
17              8           14             4            2      0
18             14           17             7            2      0
19              8           17             5            2      0
20             11           13             7            1      0
21              8           16             5            3      0
22              3           15             0            1      0
23              8           12             7            4      0
24              5           13             8            1      0
25              7            9             6            1      0
26              7           13             6            3      0
27              9           14             5            1      0
28              9           13             4            1      0
29              4           11             6            1      0
..            ...          ...           ...          ...    ...
120            26           11            33           19      2
121            13            7            25           16      2
122            33            7            41           16      2
123            20            6            25           14      2
124            24           12            33           17      2
125            29           11            36           14      2
126            19            7            24           14      2
127            18            9            25           14      2
128            21            7            32           17      2
129            29            9            34           12      2
130            31            7            37           15      2
131            34           17            39           16      2
132            21            7            32           18      2
133            20            7            27           11      2
134            18            5            32           10      2
135            33            9            37           19      2
136            20           13            32           20      2
137            21           10            31           14      2
138            17            9            24           14      2
139            26           10            30           17      2
140            24           10            32           20      2
141            26           10            27           19      2
142            15            6            27           15      2
143            25           11            35           19      2
144            24           12            33           21      2
145            24            9            28           19      2
146            20            4            26           15      2
147            22            9            28           16      2
148            19           13            30           19      2
149            16            9          

In [12]:
X = df2.drop('class',axis=1)
Y = df2['class']
X = np.asarray(X)
Y = np.asarray(Y)

In [13]:
df2.dtypes

sepal_length    int64
sepal_width     int64
petal_length    int64
petal_width     int64
class           int64
dtype: object

In [14]:
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize

In [15]:
X = df2.drop('class',axis=1)
Y = df2['class']
X = np.asarray(X)
Y = np.asarray(Y)

In [16]:
X

array([[ 8, 14,  4,  1],
       [ 6,  9,  4,  1],
       [ 4, 11,  3,  1],
       [ 3, 10,  5,  1],
       [ 7, 15,  4,  1],
       [11, 18,  7,  3],
       [ 3, 13,  4,  2],
       [ 7, 13,  5,  1],
       [ 1,  8,  4,  1],
       [ 6, 10,  5,  0],
       [11, 16,  5,  1],
       [ 5, 13,  6,  1],
       [ 5,  9,  4,  0],
       [ 0,  9,  1,  0],
       [15, 19,  2,  1],
       [14, 22,  5,  3],
       [11, 18,  3,  3],
       [ 8, 14,  4,  2],
       [14, 17,  7,  2],
       [ 8, 17,  5,  2],
       [11, 13,  7,  1],
       [ 8, 16,  5,  3],
       [ 3, 15,  0,  1],
       [ 8, 12,  7,  4],
       [ 5, 13,  8,  1],
       [ 7,  9,  6,  1],
       [ 7, 13,  6,  3],
       [ 9, 14,  5,  1],
       [ 9, 13,  4,  1],
       [ 4, 11,  6,  1],
       [ 5, 10,  6,  1],
       [11, 13,  5,  3],
       [ 9, 20,  5,  0],
       [12, 21,  4,  1],
       [ 6, 10,  5,  0],
       [ 7, 11,  2,  1],
       [12, 14,  3,  1],
       [ 6, 10,  5,  0],
       [ 1,  9,  3,  1],
       [ 8, 13,  5,  1],


In [17]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
xtrain, xtest, ytrain, ytest = train_test_split(X,Y,test_size = 0.3, random_state=0)
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(105, 4)
(105,)
(45, 4)
(45,)


In [19]:
model = LogisticRegression()
model.fit(xtrain, ytrain)
clf =  LogisticRegression().fit(xtrain,ytrain)
ypred=clf.predict(xtest)

/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [20]:
print("Accuracy:",accuracy_score(ytest, ypred))
print("Error Rate:",1-accuracy_score(ytest, ypred))

Accuracy: 0.8
Error Rate: 0.2


In [21]:
confusion_matrix(ytest,ypred)

array([[16,  0,  0],
       [ 0, 10,  8],
       [ 0,  1, 10]])

In [22]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.91      0.56      0.69        18
           2       0.56      0.91      0.69        11

   micro avg       0.80      0.80      0.80        45
   macro avg       0.82      0.82      0.79        45
weighted avg       0.85      0.80      0.80        45

