In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support,classification_report

In [2]:
df = pd.read_csv("Datasets/bank.csv")

In [5]:
df.head()

age  salary  repaid
0   70      55       1
1   96      51       1
2   86      71       1
3   87      67       1
4   77      87       1

In [10]:
X = df['age']
Y = df['repaid']

xtrain, xtest, ytrain, ytest = train_test_split(X,Y,test_size = 0.25, random_state=0)
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(2214,)
(2214,)
(738,)
(738,)


In [11]:
Y = np.array(Y).reshape(-1,1)
X = np.array(X).reshape(-1,1)

xtrain, xtest, ytrain, ytest = train_test_split(X,Y,test_size = 0.25, random_state=0)
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(2214, 1)
(2214, 1)
(738, 1)
(738, 1)


In [12]:
model = LogisticRegression()
model.fit(xtrain, ytrain)


/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [13]:
clf =  LogisticRegression().fit(xtrain,ytrain)
ypred=clf.predict(xtest)
print("Accuracy:",accuracy_score(ytest, ypred))
print("Error Rate:",1-accuracy_score(ytest, ypred))

Accuracy: 0.80352303523
Error Rate: 0.19647696477


/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
confusion_matrix(ytest,ypred)

array([[134,  94],
       [ 51, 459]])

In [15]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.72      0.59      0.65       228
           1       0.83      0.90      0.86       510

   micro avg       0.80      0.80      0.80       738
   macro avg       0.78      0.74      0.76       738
weighted avg       0.80      0.80      0.80       738



In [17]:
import statsmodels.formula.api as sm
 
model = sm.Logit(Y, X)
 
result = model.fit()


Optimization terminated successfully.
         Current function value: 0.548680
         Iterations 5


In [19]:
result.pvalues

array([  1.27070063e-152])

In [37]:
result.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                         Results: Logit
================================================================
Model:              Logit            No. Iterations:   5.0000   
Dependent Variable: y                Pseudo R-squared: 0.119    
Date:               2019-03-27 17:04 AIC:              3241.4062
No. Observations:   2952             BIC:              3247.3964
Df Model:           0                Log-Likelihood:   -1619.7  
Df Residuals:       2951             LL-Null:          -1837.8  
Converged:          1.0000           Scale:            1.0000   
-------------------------------------------------------------------
        Coef.     Std.Err.       z       P>|z|     [0.025    0.975]
-------------------------------------------------------------------
x1      0.0176      0.0007    26.3156    0.0000    0.0163    0.0189
================================================================

"""

Null Deviance
Residual deviance
P value
Fisher score
AIC                   
Degree of freedom

In [31]:
coefficients = result.params
coefficients

array([ 0.01762095])

In [44]:
#Odd Ratio
print(np.exp(result.params))

[ 1.01777711]


In [45]:
X = df.drop('repaid', axis=1)
Y = df['repaid']
xtrain, xtest, ytrain, ytest = train_test_split(X,Y,test_size = 0.25, random_state=0)
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(2214, 2)
(2214,)
(738, 2)
(738,)


In [46]:
model = LogisticRegression()
model.fit(xtrain, ytrain)

/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [47]:
clf =  LogisticRegression().fit(xtrain,ytrain)
ypred=clf.predict(xtest)
print("Accuracy:",accuracy_score(ytest, ypred))
print("Error Rate:",1-accuracy_score(ytest, ypred))

Accuracy: 0.884823848238
Error Rate: 0.115176151762


/home/divya/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [48]:
confusion_matrix(ytest,ypred)

array([[182,  46],
       [ 39, 471]])

In [49]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.82      0.80      0.81       228
           1       0.91      0.92      0.92       510

   micro avg       0.88      0.88      0.88       738
   macro avg       0.87      0.86      0.86       738
weighted avg       0.88      0.88      0.88       738



In [50]:
import statsmodels.formula.api as sm
 
model = sm.Logit(Y, X)
 
result = model.fit()


Optimization terminated successfully.
         Current function value: 0.547991
         Iterations 5


In [52]:
result.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                         Results: Logit
================================================================
Model:              Logit            No. Iterations:   5.0000   
Dependent Variable: repaid           Pseudo R-squared: 0.120    
Date:               2019-03-27 17:19 AIC:              3239.3363
No. Observations:   2952             BIC:              3251.3168
Df Model:           1                Log-Likelihood:   -1617.7  
Df Residuals:       2950             LL-Null:          -1837.8  
Converged:          1.0000           Scale:            1.0000   
------------------------------------------------------------------
          Coef.    Std.Err.      z      P>|z|     [0.025    0.975]
------------------------------------------------------------------
age       0.0203     0.0015   13.6513   0.0000    0.0174    0.0232
salary   -0.0028     0.0014   -2.0168   0.0437   -0.0055   -0.0001
================================================================

"""

In [53]:
result.pvalues

age       1.983310e-42
salary    4.371442e-02
dtype: float64

In [54]:
coefficients = result.params
coefficients

age       0.020268
salary   -0.002765
dtype: float64

In [55]:
#Odd Ratio
print(np.exp(result.params))

age       1.020474
salary    0.997239
dtype: float64
